//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeshDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Animesh
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "this feild is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "this feild is required")]
        public int Year { get; set; }
        public string Plot { get; set; }
        public string Poster { get; set; }
    }
}
